### ISSUE TITLE
Error on namespace?

### ISSUE THREAD

**Issue by niklassaers** [facebook/FBAllocationTracker#1]
I've added the following to my Podfile

```
pod 'FBRetainCycleDetector'
pod 'FBAllocationTracker'
```

pod install, my project still compiles fine. Now I add to main.m

`#import <FBAllocationTracker/FBAllocationTrackerManager.h>`

Build fails now, in FBAllocationTrackerFunctors.h line 12 with 

> Unknown typename 'namespace'

FBAllocationTrackerImpl.h also complains about line 10, 

> 'unordered_map' file not found

Is there a dependency I've missed to my project?

**Comment by kastiglione** [comment]
`FBAllocationTrackerManager.h` contains C++. The file you import it into needs to be ObjC++, which can be done by changing its file extension to `.mm`.

**Comment by gricha** [comment]
Are you using frameworks in your Podfile? This issue arised when people use frameworks and I'm fixing it right now. `FBAllocationTracker` does contain C++, but it shouldn't be explicitly imported in `FBAllocationTrackerManager.h`, so this error, ideally, shouldn't happen.

**Comment by niklassaers** [comment]
Thanks @kastiglione, I'll rename main.m to main.mm for now, then.

Thanks @Gricha, yes, I'm using frameworks in my project and Podfile.

**Comment by gricha** [comment]
@niklassaers It should be resolved as of version `0.1.2` of Allocation Tracker. as well as just latest version of FBRetainCycleDetector/FBMemoryProfiler.

https://github.com/facebook/FBMemoryProfiler/issues/1 referenced the same issue.

I will keep it open until we confirm the fix is working for you.

**Comment by niklassaers** [comment]
@Gricha Wonderful, updated to 0.1.2 and the problem is solved. :-) Thanks, guys!
