### ISSUE TITLE
Problem about FBAllocationTrackerManager

### ISSUE THREAD

**Issue by without2002** [facebook/FBAllocationTracker#9]
Hello, I have used FBRetainCycleDetector, FBAllocationTracker, and FBMemoryProfiler to find retain cycle question in my project. But I found some crash or bug in my app. So I debug it, and find the reason. There is a strong reference in method:
- (nullable NSArray *)instancesForClass:(nonnull __unsafe_unretained Class)aCls
                         inGeneration:(NSInteger)generation;

The object that track by FBAllocationTrackerManager will be reference by the return value NSArray. So it makes some objects delay to dealloc or dealloc in uncertain thread. But in the implement of FBAllocationTrackerManager the reference of tracked object is weak. When I change the implement of function instancesForClass:inGeneration: to 
- (std::vector<__weak id>)instancesForClassEx:(nonnull __unsafe_unretained Class)aCls
  inGeneration:(NSInteger)generation;

the crash and the bug have gone.
I am not sure that there is any reason to make the return value be a strong reference?

**Comment by gricha** [comment]
I'm not sure what the decision making was around that, but one of the reasons might have been to keep `FBAllocationTrackerManager` not using any C++ in headers so it can be imported by purely Objective-C code. I am not sure though whether there was any other reasons, or any other crashes that might've resulted from that, but it's definitely something that we could re-evaluate.

**Comment by without2002** [comment]
Thank you all the same, I have changed the method already in my project. And it goes well. :-D
